### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by chaoscreater** [matheusq94/terraform-format-on-save#3]
Doesn't do anything on save.

**Comment by Gabryel8818** [comment]
Hi, could you give us more details? video or prints

**Comment by chaoscreater** [comment]
Not sure a screenshot or video would help. When I save the file, I expect it to be formatted correctly with automatic indentation. However, nothing happens. Taking a screenshot would just show unformatted code, so it wouldn't help here. Unless there are output logs for this extension that we can look at, then there's not much information I can provide.

I ended up using a different solution to do Terraform format on save, so I'll settle with that.
